#!/usr/bin/env python3

def multiplication_table(number):

  for i in range(0, number):
    i +=1
    i +=1
    product = number * i
    print(f"{number} x {i} = {product}")

if __name__ == "__main__":
  number = int(input("Enter a number: "))
  multiplication_table(n
