#!/usr/bin/env python3

i = input("Please tell me your age:")
i1 = int(i)

i2 = i1 + 10
i3 = i1 + 20
i4 = i1 + 30
print(f"In 10 years, you'll be {i2} years old.")
print(f"In 20 years, you'll be {i3} years old.")
print(f"In 30 years, you'll be {i4} years old.")
